Weather app upgrade
Tototyr/weather-app pull request #3
Opened 2023-03-23 23:48 UTC by Tototyr

2023-03-23 23:50 UTC, Tototyr commented on src/components/Search/search.jsx
> +            {prompts.length > 0 && (
при проверке prompts.length > 0 && showprompts ломалась   onClick={() => handlePromptsClick(prompt.name)}
не понимаю почему

2023-03-24 04:25 UTC, dudeinhoodie requested changes

2023-03-24 04:25 UTC, dudeinhoodie commented on src/components/Search/search.jsx
> +            .catch((error) => console.log(error));
ошибки давай обрабатывать и писать в стейт, чтобы было понятно что запрос закрашился и нужно попрбовать снова

2023-03-24 04:25 UTC, dudeinhoodie commented on src/components/Search/search.jsx
> +            .then((data) => setPrompts(data.slice(0, 4)))
а почему решил обрезать по 4 элементу, а не показывать все?

2023-03-24 04:25 UTC, dudeinhoodie commented on src/components/Search/search.jsx
> +            .catch((error) => console.log(error));
давай отделять колеты от мух

управление инпутом (изменение значения, сброс, и тд)  – отдельная функция
запрос к апишке – тоже отдельная функция

давай мы перепишем все на хуки, заодно разберешься с ними

смотри, прделагаю добавить хук `useSearch()` который будет возвращать состояние инутпа и хендлер для его изменения
и давай заведем хук `useCities()` который будет принимать value инпута и делать запрос, когда оно изменится, но с дебанусом, сюда-то мы его и прикрутим, но давай пойдем от простого 👇

я хочу чтобы разобрался с тем как работает `useEffect` и `useCallback` хук из `React` и сделал так, чтобы на изменения инпут `value` срабатывал запрос к апишке, как сделаешь – потом прикрутим дебаунс

2023-03-24 04:25 UTC, dudeinhoodie commented on src/components/Search/search.jsx
> +                onBlur={() => setShowPromts(false)}
не надо юзать () => {} в ренедере компонента, так на каждый реднер (а их много) будет создаваться новая функция, что плохо влияет на перфоманс, выноси в useCallback

2023-03-24 04:25 UTC, dudeinhoodie commented on src/components/Search/search.jsx
> +                onBlur={() => setShowPromts(false)}
вместо того. чтобы писать setShowPromts(true) и setShowPromts(false) можно сделать функциию togglePromts которая будет переключать значение на противоположенное 

```tooglePromts() {
setShowPromts(!showprompts)
}```

2023-03-24 04:25 UTC, dudeinhoodie commented on src/components/Search/search.jsx
> +    const [showprompts, setShowPromts] = useState(false);
пиши в camelCase

2023-03-24 04:25 UTC, dudeinhoodie commented on src/components/Search/search.jsx
> +    const [showprompts, setShowPromts] = useState(false);
чаще всего, если значение стейта булево то принято использовать именование типа `isVisible`, `isActive`, `etc`
но в целом можно оставить и как ты сделал, только сделай в camelCase

2023-03-24 13:40 UTC, Tototyr commented on src/components/Search/search.jsx
> +            .then((data) => setPrompts(data.slice(0, 4)))
там вылазит по 10-15 разных городов и это смотрится очень коряво ну и я решил что удобнее и красивее будет на 4 поделить

2023-03-24 13:41 UTC, Tototyr commented on src/components/Search/search.jsx
> +            .catch((error) => console.log(error));
хорошо, переделаю

2023-04-01 05:55 UTC, closed without merging